apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-web
  namespace: demo
  labels:
    app: frontend-web
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-web
  template:
    metadata:
      labels:
        app: frontend-web
        component: frontend
    spec:
      containers:
      - name: web
        image: myapp/frontend:v1.0.5
        ports:
        - containerPort: 3000
        env:
        - name: API_URL
          value: "http://backend-api-service"
        - name: APP_CONFIG
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: frontend.config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
