---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
  labels:
    environment: demo
    team: platform
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: demo
  labels:
    app: shared-config
    component: shared
data:
  database.host: "postgres.demo.svc.cluster.local"
  database.port: "5432"
  database.name: "myapp"
  frontend.config: |
    {
      "apiUrl": "http://backend-api-service/api",
      "features": {
        "darkMode": true,
        "analytics": false
      },
      "version": "1.0.5"
    }
  app.properties: |
    # Application configuration
    server.port=8080
    logging.level.root=INFO
    logging.level.com.myapp=DEBUG
    
    # Cache settings
    cache.ttl=300
    cache.max-size=1000
