apiVersion: v1
kind: Service
metadata:
  name: backend-api-service
  namespace: demo
  labels:
    app: backend-api
    component: backend
spec:
  selector:
    app: backend-api
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP
