apiVersion: v1
kind: Service
metadata:
  name: web-frontend-service
  namespace: default
  labels:
    app: web-frontend
    tier: frontend
spec:
  selector:
    app: web-frontend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  type: LoadBalancer
  sessionAffinity: ClientIP
